#!/bin/bash

enable_bash_completion() {
	if [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
}

load_dotfiles() {
    declare -a files=(
        $HOME/dotfiles/shell/bash_options # Options
        $HOME/dotfiles/shell/bash_exports # Exports
        $HOME/dotfiles/shell/bash_aliases # Aliases
        $HOME/dotfiles/shell/functions/* # Functions
        $HOME/dotfiles/shell/bash_prompt # Custom bash prompt
        $HOME/dotfiles/shell/bash_paths # Path modifications
        $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

enable_bash_completion
unset enable_bash_completion

load_dotfiles
unset load_dotfiles

